
name: First Workflow
on: workflow_dispatch           #Events that should be run
#This paticular event is used to manually start the worflow by user

jobs:
  first-job:    #Job Name
    runs-on: ubuntu-latest  #Runner which job will runs on   #Reserved name
    steps:                #Reserved name
      - name: Print Greeting
        run: echo "Hello World"
      - name: Calculation
        run: |               #Pipe Symbol(|) is used to run multiple shell commands
            expr 2+1
            echo "result is displayed"
            echo "the result is $x"
      - name: Print Good Bye
        run: echo "Done-Bye"


